# Site settings
title: cuekoo
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Written by desire of Edward. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cuekoo.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cuekoo

# Build settings
markdown: kramdown
highlighter: pygments
